[lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "C90",
    "N",
    "I",
    "PD",
    "PL",
    "RUF",
    "ANN",
    "B",
    "LOG",
    "G",
]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
